### ISSUE TITLE
Examples are missing

### ISSUE THREAD

**Issue by Jignesh-UI** [chriscalip/d3.js.tutorials#5]
Few of Examples are missing.

**Comment by chriscalip** [comment]
Please be specific on which examples are missing.

**Comment by akshaygoyal88** [comment]
@chriscalip Thanks for wonderful tutorials
below scripts are missing
http://chriscalip.github.io/d3.js.tutorials/17.html
http://chriscalip.github.io/d3.js.tutorials/18.html

**Comment by chriscalip** [comment]
@Jignesh-UI @Jignesh-UI 
I am accepting Pull Request.
